
export const NEW_JOB_REQUEST = "NEW_JOB_REQUEST";
export const NEW_JOB_SUCCESS = "NEW_JOB_SUCCESS";
export const NEW_JOB_FAIL = "NEW_JOB_FAIL";

export const ALL_JOB_REQUEST = "ALL_JOB_REQUEST";
export const ALL_JOB_SUCCESS = "ALL_JOB_SUCCESS";
export const ALL_JOB_FAIL = "ALL_JOB_FAIL";

export const ADMIN_JOB_REQUEST = "ADMIN_JOB_REQUEST";
export const ADMIN_JOB_SUCCESS = "ADMIN_JOB_SUCCESS";
export const ADMIN_JOB_FAIL = "ADMIN_JOB_FAIL";

export const DELETE_JOB_REQUEST = "DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAIL = "DELETE_JOB_FAIL";
export const DELETE_JOB_RESET = "DELETE_JOB_RESET";

export const UPDATE_JOB_REQUEST = "UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS = "UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAIL = "UPDATE_JOB_FAIL";
export const UPDATE_JOB_RESET = "UPDATE_JOB_RESET";

export const JOB_DETAILS_REQUEST = "JOB_DETAILS_REQUEST";
export const JOB_DETAILS_SUCCESS = "JOB_DETAILS_SUCCESS";
export const JOB_DETAILS_FAIL = "JOB_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const  NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const  ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const  DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";



export const CLEAR_ERRORS = "CLEAR_ERRORS";
