
export const NEW_CATOGERY_REQUEST = "NEW_CATOGERY_REQUEST";
export const NEW_CATOGERY_SUCCESS = "NEW_CATOGERY_SUCCESS";
export const NEW_CATOGERY_FAIL = "NEW_CATOGERY_FAIL";

export const ALL_CATOGERY_REQUEST = "ALL_CATOGERY_REQUEST";
export const ALL_CATOGERY_SUCCESS = "ALL_CATOGERY_SUCCESS";
export const ALL_CATOGERY_FAIL = "ALL_CATOGERY_FAIL";

export const ADMIN_CATOGERY_REQUEST = "ADMIN_CATOGERY_REQUEST";
export const ADMIN_CATOGERY_SUCCESS = "ADMIN_CATOGERY_SUCCESS";
export const ADMIN_CATOGERY_FAIL = "ADMIN_CATOGERY_FAIL";

export const DELETE_CATOGERY_REQUEST = "DELETE_CATOGERY_REQUEST";
export const DELETE_CATOGERY_SUCCESS = "DELETE_CATOGERY_SUCCESS";
export const DELETE_CATOGERY_FAIL = "DELETE_CATOGERY_FAIL";
export const DELETE_CATOGERY_RESET = "DELETE_CATOGERY_RESET";

export const UPDATE_CATOGERY_REQUEST = "UPDATE_CATOGERY_REQUEST";
export const UPDATE_CATOGERY_SUCCESS = "UPDATE_CATOGERY_SUCCESS";
export const UPDATE_CATOGERY_FAIL = "UPDATE_CATOGERY_FAIL";
export const UPDATE_CATOGERY_RESET = "UPDATE_CATOGERY_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
